Add myself to ios list
Babylonpartners/ios-playbook pull request #235
Opened 2019-09-10 14:08 UTC by thargett-babylon

2019-09-10 14:12 UTC, danspndl requested changes
Please follow the steps at the beginning of the table (update [scripts/squad.yml](https://github.com/Babylonpartners/ios-playbook/blob/master/scripts/squads.yml) then run [squads.rb](https://github.com/Babylonpartners/ios-playbook/blob/master/scripts/squads.rb)) (#225)

2019-09-10 14:13 UTC, mluisbrown commented on README.md
> +      <tr><td>Tyler Hargett</td><td><a href='https://github.com/thargett-babylon'>@thargett-babylon</a></td><td></td></tr>
There's something off with the column alignment:

![image](https://user-images.githubusercontent.com/4175766/64621328-66f3d600-d3dd-11e9-96a2-307c96097e4d.png)

You probably need to increase the `rowspan` at line 100 to 4.

2019-09-10 14:14 UTC, mluisbrown submitted a review, later dismissed
Small formatting issue.

2019-09-10 14:15 UTC, mluisbrown commented
Ok, looks like @sdaniel55 has the proper solution 😄

2019-09-10 16:16 UTC, danspndl approved these changes
Welcome to the team 🚀

2019-09-11 16:18 UTC, Daniel1of1 approved these changes
👋 Welcome

2019-09-12 15:10 UTC, merged