[Danger Rules] Documentation for #11280
Babylonpartners/ios-playbook pull request #367
Opened 2020-04-02 17:24 UTC by AliSoftware

Doc for https://github.com/babylonhealth/babylon-ios/pull/11280

2020-04-02 17:26 UTC, danspndl approved these changes
✨

2020-04-02 17:28 UTC, AliSoftware commented on Cookbook/Technical-Documents/DangerRules.md
> +(If still detects `Feedbacks` called conditionally though –like `if (cond) { feedbacks += Self.whenBlah() }`– and should still catch the most common cases of forgiving to add a newly-created `Feedbac
```suggestion
(If still detects `Feedbacks` called conditionally though –like `if (cond) { feedbacks += Self.whenBlah() }`– and should still catch the most common cases of forgetting to add a newly-created `Feedback` to the state machine.
```

2020-04-02 23:56 UTC, NSMyself submitted a review, later dismissed

2020-04-02 23:58 UTC, NSMyself requested changes
Very minor thing but I think you mean `It` instead of `If`

2020-04-02 23:58 UTC, NSMyself commented on Cookbook/Technical-Documents/DangerRules.md
> +(If still detects `Feedbacks` called conditionally though –like `if (cond) { feedbacks += Self.whenBlah() }`– and should still catch the most common cases of forgetting to add a newly-created `Feedba
```suggestion

(It still detects `Feedbacks` called conditionally though – like `if (cond) { feedbacks += Self.whenBlah() }` – and should still catch the most common cases of forgetting to add a newly-created `Feedback` to the state machine)
```

2020-04-03 06:47 UTC, AliSoftware commented on Cookbook/Technical-Documents/DangerRules.md
> +(If still detects `Feedbacks` called conditionally though –like `if (cond) { feedbacks += Self.whenBlah() }`– and should still catch the most common cases of forgetting to add a newly-created `Feedba
Good eye!

2020-04-03 08:14 UTC, konrad-em approved these changes
👍

2020-04-03 08:42 UTC, NSMyself approved these changes

2020-04-03 08:42 UTC, merged