Document the debug window.
Babylonpartners/ios-playbook pull request #89
Opened 2019-04-11 13:57 UTC by andersio

2019-04-11 15:10 UTC, RuiAAPeres commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +It always stands by and wait for you call — either
I don't understand this sentence.

2019-04-11 15:10 UTC, RuiAAPeres commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +You want to have an early way out to this prolonged, endured process of having to repeat yourselves just to get through them.
Maybe a less a dramatic sentence? 😛

2019-04-11 15:13 UTC, RuiAAPeres commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +All `DebugAction` has a title, which need not be localized. You may configure them to be either of these three forms:
`All `DebugAction` has a title` ➡️ `All `DebugAction` have a title`

2019-04-15 09:03 UTC, Ben-Henshall commented
I currently have a PR open that affects the documentation for this tool, so please do not merge until that branch has been merged (#7228), so that I can update the documentation.

2019-04-15 23:13 UTC, andersio commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +You want to have an early way out to this prolonged, endured process of having to repeat yourselves just to get through them.
Why

2019-04-16 12:17 UTC, Ben-Henshall commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +It always stands by and wait for you call — either
```suggestion
The debug window can be activated in the following ways:
```

2019-04-16 12:18 UTC, Ben-Henshall commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +All `DebugAction` has a title, which need not be localized. You may configure them to be either of these three forms:
```suggestion
All `DebugAction` have a title, which need not be localized. You may configure them to be either of these three forms:
```

2019-04-16 12:19 UTC, Ben-Henshall commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +It always stands by and waits for you call — either
```suggestion
The debug window can be activated in the following ways:
```

2019-04-16 16:27 UTC, Ben-Henshall commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +It always stands by and wait for you call — either
fixed

2019-04-17 00:05 UTC, NSMyself approved these changes
Nice write-up 👍

2019-04-17 05:51 UTC, inamiy requested changes
This document is an ideal version which I think this needs to pass the proposal first.

I still don't get what will be the differences from current state.
(There should be more 🚧 printed in current 8d87703 documentation)

2019-04-17 05:56 UTC, inamiy commented
Or, we can review the actual implementation first, then this documentation.

2019-04-17 08:57 UTC, Ben-Henshall commented
@inamiy I can remove the 🚧  parts for now, and ask for feedback on other possible improvements.
I'm not sure if this warrants a proposal though, considering they are minor improvements to an existing system?

2019-04-17 09:54 UTC, andersio commented
@inamiy I asked @RuiAAPeres and the conclusion was that there is no proposal for this, since both debug functionalities covered by the document already exist for a fairly long time. The ideal state is just unifying the implementations of both.

2019-04-17 09:58 UTC, andersio commented
For @inamiy and others stumbled upon this document, as noted in the document, there are only three parts not implemented yet:

1. `FormsViewController` forwarding `DebugActionsProviding` calls to its View Model.
2. Extend the Debug Window infrastructure to support shake, and move all shake-to-fill actions to be under the same umbrella.
3. "Share Quick Info" button.

2019-04-17 10:02 UTC, inamiy commented
My current understanding is:

- "Shake" and "debug menu" is different
- This proposal is trying to make "shake" as shortcut for opening "debug menu"
- There is no "ubiquitous action" yet

so current state and ideal state are quite far apart now... Am I right?

I think the best flow would be: 1. proposal -> 2. implementation -> 3. documentation.
If we skip proposal, we want to see real implementation before merging this documentation.
Just let me know, am I taking a right step on this? (or too verbose?)

2019-04-17 10:05 UTC, andersio commented
I don't mind taking out the "to-be-done" bits as a separate branch if that's desired.

> There is no "ubiquitous action" yet
This bit is in already.

2019-04-17 10:15 UTC, inamiy commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +* Date action - A one-off closure that retrieves a selected (optional) date. You could also provide an initially selected date.
Is this related to `DebugAction` ? 
It seems it relates to "debug window" alongside "gender picker" though.

2019-04-17 10:22 UTC, Ben-Henshall commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +* Date action - A one-off closure that retrieves a selected (optional) date. You could also provide an initially selected date.
Sort of.

The date picker has been in there for a while (component showcase) is separate from any debug actions. I'm not sure if we need to keep it in there any longer to be honest.

A new `DebugAction` was added a few days ago that included this date action, which looks the same as the component showcase version, but can be used by screens to set certain date-related flags.

2019-04-17 10:28 UTC, inamiy commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +* Date action - A one-off closure that retrieves a selected (optional) date. You could also provide an initially selected date.
I'm only seeing the type `DebugAction` and `DebugAction.Action` as a proof-of-concept, so I think we should not include information unrelated to these types.

2019-04-17 10:29 UTC, Ben-Henshall commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +* Date action - A one-off closure that retrieves a selected (optional) date. You could also provide an initially selected date.
Sorry, I should clarify. `date` *is* a `DebugAction.Action` case. By "sort of", I meant that it looks identical to the component showcase picker (which has 0 function)

2019-04-17 10:32 UTC, inamiy commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +* Date action - A one-off closure that retrieves a selected (optional) date. You could also provide an initially selected date.
OK, maybe we can move date-picker as another `DebugAction` with some special flag to place at the bottom? 🤔 

I still want to see it appearing in real code somehow, but for now, I think I understand the similar concept, so I will move on 👍

2019-04-17 10:32 UTC, inamiy approved these changes

2019-04-17 10:33 UTC, Ben-Henshall commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +* Date action - A one-off closure that retrieves a selected (optional) date. You could also provide an initially selected date.
This is already in code: #7228 (in Babylon repo)

2019-04-17 12:31 UTC, inamiy commented on Cookbook/Technical-Documents/TheDebugWindow.md
> +* Date action - A one-off closure that retrieves a selected (optional) date. You could also provide an initially selected date.
Oh I was looking at wrong branch... #7228 solves my issue 👍

2019-04-17 15:42 UTC, merged